---
name: Build Containers
on:
  push:
    paths:
      - .github/workflows/docker.yml
      - "docker/**"
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - "docker/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.AZURE_CR_URL }}
          username: ${{ vars.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_TOKEN }}

      - name: Build CI/CD image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/gh-actions.dockerfile
          tags: ${{ vars.AZURE_CR_URL }}/pyshell-test:latest
          push: ${{ github.ref == 'refs/heads/master' }}
...
